site_name: ContaPortable Docs
site_description: Documentación de ContaPortable 
site_url: https://docs.contaportable.com

theme:
  name: material
  language: es
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: orange
      accent: blue
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: blue
      accent: orange
  features:
    - content.code.copy
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - search.highlight
  icon: 
      repo: fontawesome/brands/gitkraken
nav:
  - Inicio: index.md
  - Módulos:
      - 🏦Bancos: 
        - Gestión de bancos, cuentas y chequeras: modulos/bancos/mantenimiento_bancos_cuentas_chequeras.md
        - Conciliación Bancaria: modulos/bancos/Conciliacionbancaria.md
        - Transferencias Bancarias: modulos/bancos/transferenciasBancarias.md
      - 📑Facturación:
        - Dual: modulos/facturacion/facturacion_dual.md
        - Multilínea: modulos/facturacion/facturacion_lineas_multiples.md
        - Personalizar secuencia de generación DTE: modulos/facturacion/personalizar_secuencia_gen_dte.md
        - Importar Clientes y Facturas desde plantilla Excel: modulos/facturacion/importar_clientes_desde_plantilla.md
        - Configurar links de Pago: 
          - Wompi: modulos/facturacion/linksPago/wompi/linkPagoWompi.md
        - Gestión de CXC: modulos/facturacion/gestion_cuentas_por_cobrar.md
        - Configurar Email para envio de DTE o cotización: modulos/facturacion/configMultiProvEmail.md 
        - Activar autorización al aplicar descuentos por item y globales: modulos/facturacion/bloqueo_descuentos.md 
        - Personaliza nomenclatura para archivos del DTE al exportarlos: modulos/facturacion/nomenclatura_dte.md
        - Creación de correlativos automáticos: modulos/facturacion/correlativosAutomaticos.md
        - Creación de Apéndices VN: modulos/facturacion/apendicesVN.md
      - 🛒Compras (OG Y OC):
        - Gestión de CXP: modulos/compras/gestion_cuentas_por_pagar.md
        - Importar Json del DTE en OG: modulos/compras/importJsonOG.md
        - Registrar OG de vehículos: modulos/compras/OG_mantenimiento_vehiculos.md
      - 📦Inventario:
        - Gestión de familias de inventario: modulos/inventario/FamiliaInventario.md
      - 📘Contabilidad:
        - Contabilización Automática: modulos/contabilidad/contabilizacion_automatica.md
        - Control de períodos contables: modulos/contabilidad/control_periodos_usuario.md
      - 📊Reportes:
        - Introducción: Reports/reportes.md
        - Clientes: 
          - Reportes de clientes: Reports/categorias/clientes.md
          - Interfaz de gestión y envío de avisos de cobro: Reports/categorias/CLI1H.md
        - Inventario: Reports/categorias/inventario.md
        - Impuestos: Reports/categorias/impuestos.md
        - 📈Reportes Gerenciales:
            - Reporte de mantenimiento de vehículos: Reports/reportesGerenciales/reporte_mantenimiento_vehiculos.md
      - 🧾Informes (Anexos):
        - F07:
          - Generales: modulos/Informes_anexos/F07/anexos_f07.md
          - Reportes: modulos/Informes_anexos/F07/reportes.md
          - Agrupar CSV de anexo vtas Consu. Final: modulos/Informes_anexos/F07/agrupacionAnexoConsumidorFinal.md
        - F14: 
          - Anexo de retenciones de renta: modulos/Informes_anexos/F14/anexos_f14.md
          - Anexo de pago de quincena 25: modulos/Informes_anexos/F14/anexos_f14Q25.md
        - Importacion de Json Optimizada: modulos/Informes_anexos/importacionJsonAnexos.md
      - 👥Planillas: 
        - Módulo de planillas: modulos/planillas/planillas.md
        - Quincena 25: modulos/planillas/planillas_Q25.md
      - ⚙️Parámetros en Contaportable:
        - Informes/Anexos: Parametros/Modulos/Informes_anexos/ParametrosEnAnexos.md
        - Generales: Parametros/ParametrosGenerales.md
        - Activar Informes/Anexos en sistemas de facturación: Parametros/Modulos/Facturación/activarModInformes.md
  - CP365 (Otros Módulos):
    - 📦Instalador de otros módulos: modulos/cp365/instaladorModulesCp365.md 
    - 💧ConAgua: modulos/cp365/ConAgua/conAgua.md
      


repo_url: https://github.com/contaportable/CPDOCS
repo_name: Documentación de ContaPortable

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg # Base de datos de emojis
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.keys # Para dibujar teclas dentro de las páginas

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid  # Sirve para implementar diagramas por medio de sintaxis Mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format 

  - pymdownx.tabbed:
      alternate_style: true   
   
  - pymdownx.critic

plugins:
  - glightbox  # Plugin para manejar imágenes con zoom
  - search     # Plugin de búsqueda

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # Para renderizar fórmulas matemáticas

extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/contaportable
    - icon: simple/facebook
      link: https://facebook.com/contaportable
    - icon: simple/instagram
      link: https://www.instagram.com/contaportablesv/
    - icon: simple/tiktok
      link: https://www.tiktok.com/@contaportable

copyright: Copyright &copy; 2026 ContaPortable - Yuri Ernesto Calderón Rodríguez